const dataProjects = [{
  projectTitle: 'Project name goes here',
  popupLanguages: ['HTML/CSS', 'Ruby on Rails', 'Javascript', 'React'],
  imgShow: ['./img/project1.png', './img/project1.png', './img/project1.png', './img/project1.png'],
  pText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.<br>Ut aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
  liveUrl: 'https://antoniohincapie.github.io/My_Portfolio/',
  sourceUrl: 'https://github.com/AntonioHincapie/My_Portfolio',
},
{
  projectTitle: 'Project name goes here',
  popupLanguages: ['HTML/CSS', 'Ruby on Rails', 'Javascript'],
  imgShow: ['./img/project2.png', './img/project2.png', './img/project2.png', './img/project2.png'],
  pText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.<br>Ut aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
  liveUrl: 'https://antoniohincapie.github.io/My_Portfolio/',
  sourceUrl: 'https://github.com/AntonioHincapie/My_Portfolio',
},
{
  projectTitle: 'Project name goes here',
  popupLanguages: ['HTML/CSS', 'Ruby on Rails', 'Javascript', 'React'],
  imgShow: ['./img/project3.png', './img/project3.png', './img/project3.png', './img/project3.png'],
  pText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.<br>Ut aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
  liveUrl: 'https://antoniohincapie.github.io/My_Portfolio/',
  sourceUrl: 'https://github.com/AntonioHincapie/My_Portfolio',
},
{
  projectTitle: 'Project name goes here',
  popupLanguages: ['HTML/CSS', 'Ruby on Rails', 'Javascript'],
  imgShow: ['./img/project4.png', './img/project4.png', './img/project4.png', './img/project4.png'],
  pText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.<br>Ut aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
  liveUrl: 'https://antoniohincapie.github.io/My_Portfolio/',
  sourceUrl: 'https://github.com/AntonioHincapie/My_Portfolio',
},
{
  projectTitle: 'Project name goes here',
  popupLanguages: ['HTML/CSS', 'Ruby on Rails', 'Javascript'],
  imgShow: ['./img/project5.png', './img/project5.png', './img/project5.png', './img/project5.png'],
  pText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.<br>Ut aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
  liveUrl: 'https://antoniohincapie.github.io/My_Portfolio/',
  sourceUrl: 'https://github.com/AntonioHincapie/My_Portfolio',
},
{
  projectTitle: 'Project name goes here',
  popupLanguages: ['HTML/CSS', 'Ruby on Rails', 'Javascript'],
  imgShow: ['./img/project6.png', './img/project6.png', './img/project6.png', './img/project6.png'],
  pText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.<br>Ut aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
  liveUrl: 'https://antoniohincapie.github.io/My_Portfolio/',
  sourceUrl: 'https://github.com/AntonioHincapie/My_Portfolio',
}];
export default dataProjects;